- name: ensure target directory exist
  file:
    path: "{{ service_directory_target }}"
    state: directory
    mode: 0755
  become: yes

- set_fact:
    s3_tmp_file: "/tmp/{{ bundle_s3_bucket | to_uuid }}.tar.gz"

- name: download and extract bundle
  become: yes
  block:
    - name: download archive to temporary file
      aws_s3:
        bucket: "{{ bundle_s3_bucket }}"
        object: "{{ bundle_s3_object }}"
        dest: "{{ s3_tmp_file }}"
        mode: get
    - name: extract bundle to target directory
      unarchive:
        src: "{{ s3_tmp_file }}"
        remote_src: yes
        dest: "{{ service_directory_target }}"
        owner: root
        group: root

  always:
    - name: remove temporary file
      file:
        path: "{{ s3_tmp_file }}"
        state: absent

- name: set current version
  file:
    state: link
    src: "{{ service_directory_target }}"
    dest: "{{ service_directory_current }}"
    force: yes
  become: yes
